require("jackson.plugins-setup")

-- Configs
require("jackson.config.autocmds")
require("jackson.config.colorscheme")
require("jackson.config.keymaps")
require("jackson.config.options")

-- Plugins
require("jackson.plugins.alpha")
require("jackson.plugins.autopairs")
require("jackson.plugins.bufferline")
require("jackson.plugins.cmp")
require("jackson.plugins.colorizer")
require("jackson.plugins.comment")
require("jackson.plugins.easypick")
require("jackson.plugins.flash")
require("jackson.plugins.gitsigns")
require("jackson.plugins.lsp")
require("jackson.plugins.lualine")
require("jackson.plugins.neo-tree")
require("jackson.plugins.noice")
require("jackson.plugins.nvim-bqf")
require("jackson.plugins.nvim-ufo")
require("jackson.plugins.persisted")
require("jackson.plugins.telescope")
require("jackson.plugins.toggleterm")
require("jackson.plugins.transparent")
require("jackson.plugins.treesitter")
require("jackson.plugins.which-key")
