require("jackson.plugins-setup")

-- Configs
require("jackson.config.autocmds")
require("jackson.config.colorscheme")
require("jackson.config.keymaps")
require("jackson.config.options")

-- Plugins
require("jackson.plugins.alpha")
require("jackson.plugins.autopairs")
require("jackson.plugins.bufferline")
require("jackson.plugins.cmp")
require("jackson.plugins.colorizer")
require("jackson.plugins.comment")
require("jackson.plugins.copilot")
require("jackson.plugins.copilot-cmp")
require("jackson.plugins.dap-go")
require("jackson.plugins.easypick")
require("jackson.plugins.gitsigns")
require("jackson.plugins.harpoon")
require("jackson.plugins.hlargs")
require("jackson.plugins.indent-blankline")
require("jackson.plugins.flash")
require("jackson.plugins.lsp")
require("jackson.plugins.lsp-saga")
require("jackson.plugins.lualine")
require("jackson.plugins.mini")
require("jackson.plugins.statuscol")
require("jackson.plugins.nvim-ufo")
require("jackson.plugins.neo-tree")
require("jackson.plugins.noice")
require("jackson.plugins.nvim-bqf")
require("jackson.plugins.persisted")
require("jackson.plugins.project")
require("jackson.plugins.telescope")
require("jackson.plugins.toggleterm")
require("jackson.plugins.transparent")
require("jackson.plugins.treesitter")
require("jackson.plugins.typescript")
require("jackson.plugins.which-key")
