local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<C-f>", mark.add_file, { desc = "Add file to harpoon" })
vim.keymap.set("n", "<C-g>", ui.toggle_quick_menu, { desc = "Toggle harpoon menu" })
vim.keymap.set("n", "<C-e>", function()
	ui.nav_next()
end, { desc = "Navigate to next harpoon mark" })
vim.keymap.set("n", "<C-w>", function()
	ui.nav_prev()
end, { desc = "Navigate to previous harpoon mark" })
-- vim.keymap.set("n", "<A-Left>", function()
--   ui.nav_file(1)
-- end)
-- vim.keymap.set("n", "<A-Down>", function()
--   ui.nav_file(2)
-- end)
-- vim.keymap.set("n", "<A-Up>", function()
-- 	ui.nav_file(3)
-- end)
-- vim.keymap.set("n", "<A-Down>", function()
-- 	ui.nav_file(4)
-- end)
