local status_ok, transparent = pcall(require, "transparent")
if not status_ok then
	return
end

transparent.setup({
	groups = { -- table: default groups
		"Normal",
		"NormalNC",
		"Comment",
		"Constant",
		"Special",
		"Identifier",
		"Statement",
		"PreProc",
		"Type",
		"Underlined",
		"Todo",
		"String",
		"Function",
		"Conditional",
		"Repeat",
		"Operator",
		"Structure",
		"LineNr",
		"NonText",
		"SignColumn",
		"CursorLineNr",
		"EndOfBuffer",
	},
	extra_groups = {
		"NormalFloat",
		"BufferLineTabClose",
		"BufferlineBufferSelected",
		"BufferLineFill",
		"BufferLineBackground",
		"BufferLineSeparator",
		"BufferLineIndicatorSelected",
    "CursorLine",
    "CursorColumn",
		"FloatBorder",
		"FloatBorderNC",
		"Float",
    "StatusLine",
    "StatusLineNC",
		"UfoFoldedBg",
		"UfoFoldedFg",
		"UfoPreviewSbar",
		"UfoPreviewWinbar",
		"UfoCursorFoldedLine",
		"UfoPreviewCursorLine",
		"NeoTreeNormal",
		"LspSagaFinderSelection",
		"LspSagaHoverBorder",
		"LspSagaPreviewBorder",
		"TelescopePromptBorder",
		"TelescopeNormal",
		"ToolbarLine",
		"WhichKey",
		"WhichKeyFloat",
	}, -- table: additional groups that should be cleared
	exclude_groups = {}, -- table: groups you don't want to clear
})
